language: node_js

sudo: false
dist: trusty

node_js:
  - "8"
  - "9"
  - "10"

branches:
  only:
    - master
    - demo

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - npm i -g npm@latest

install:
  - travis_retry npm i

before_script:

script:
  - npm run build
  - npm run lint

git:
  depth: 1
