language: node_js

sudo: false
dist: trusty

node_js:
  - '10'

branches:
  only:
    - master
    - develop

addons:
  ssh_known_hosts: 173.212.251.237

before_install:
  - npm i -g npm@latest

install:
  - travis_retry npm i

before_script:

script:
  - npm run build
  - npm run lint

git:
  depth: 1
