language: node_js
sudo: false
dist: trusty
node_js:
  - '10'
branches:
  only:
    - master
    - develop
addons:
  ssh_known_hosts: 173.212.251.237
before_install:
  - openssl aes-256-cbc -K $encrypted_fcf78e5becdc_key -iv $encrypted_fcf78e5becdc_iv
    -in deploy_key.enc -out ./deploy_key -d
  - npm i -g npm@latest
install:
  - travis_retry npm i
before_script:
script:
  - npm run build
  - npm run lint
  - eval "$(ssh-agent -s)"
  - chmod 600 ./deploy_key
  - echo -e "Host 173.212.251.237\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - ssh-add ./deploy_key
  - ssh -i ./deploy_key root@173.212.251.237 pwd
  - scp -i ./deploy_key -r -v dist/ root@173.212.251.237:/var/www/vcare-front/dist
git:
  depth: 1
