/**
 * 1HEED APi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0-oas3
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */import { ImageData } from './imageData';
import { VideoData } from './videoData';


export interface Attachment { 
    id?: string;
    name?: string;
    size?: any;
    mimeType?: string;
    imageData?: ImageData;
    videoData?: VideoData;
    fileUrl?: string;
}