/**
 * 1HEED APi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0-oas3
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */import { Picture } from './picture';


export interface UserInfo { 
    name?: string;
    id?: string;
    userType?: UserInfo.UserTypeEnum;
    picture?: Picture;
}
export namespace UserInfo {
    export type UserTypeEnum = 'FACEBOOK';
    export const UserTypeEnum = {
        FACEBOOK: 'FACEBOOK' as UserTypeEnum
    };
}