/**
 * 1HEED APi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ProfilePicture } from './profilePicture';
import { UserIdForPage } from './userIdForPage';


export interface UserInfo { 
    firstName?: string;
    middleName?: string;
    nameFormat?: string;
    lastName?: string;
    shortName?: string;
    link?: string;
    bio?: string;
    about?: string;
    relationshipStatus?: string;
    religion?: string;
    website?: string;
    birthday?: string;
    email?: string;
    gender?: string;
    political?: string;
    locale?: string;
    username?: string;
    picture?: ProfilePicture;
    idsForPages?: Array<UserIdForPage>;
}
